# Generated by Django 3.0.4 on 2020-04-03 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN_13', models.CharField(blank=True, max_length=13, null=True)),
                ('ISBN_10', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('pubDate', models.DateField(blank=True, null=True)),
                ('coverThumbURL', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MediaUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('collection', models.ManyToManyField(blank=True, related_name='collection', to='mediaTracker.Book')),
            ],
        ),
    ]
