# Generated by Django 3.0.4 on 2020-03-11 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('author1', models.CharField(max_length=100)),
                ('author2', models.CharField(blank=True, max_length=100)),
                ('pubDate', models.DateField(blank=True, null=True)),
                ('coverThumbURL', models.URLField(blank=True, null=True)),
                ('isInPrint', models.BooleanField(default=True)),
                ('seriesName', models.CharField(blank=True, max_length=200, null=True)),
                ('seriesNum', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('collection', models.ManyToManyField(blank=True, related_name='collection', to='mediaTracker.MediaUser')),
            ],
        ),
    ]
