# Generated by Django 3.0.4 on 2020-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
