# Generated by Django 3.0.4 on 2020-03-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTracker', '0002_auto_20200312_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='collection',
        ),
        migrations.AddField(
            model_name='book',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='mediaTracker.MediaUser'),
        ),
    ]
